# CI workflow for the demo project

name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Maven Install
        run: mvn install

      - name: Upload build artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify If build Fails
        if: failure()
        run: echo "Build job failed! Please check logs for details."
      
      - name: Notify If build Succeeds
        if: success()
        run: echo "Build job succeeded! Proceeding to testing."
  
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on Other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"
    
  
  Security_Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate analysis
    
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          scan-type: 'filesystem'
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: 'os,library'
          output: 'trivy-results.json'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json